### ISSUE TITLE
--proxy=X_Forwarded_For is not working

### ISSUE THREAD

**Issue by snap9** [snapframework/snap-server#90]
Problem: The IP address logged into the file given by `--access-log=<logfile>` is recording `127.0.0.1` instead of the real visitor IP address. This happens even if I specify `--proxy=X_Forwarded_For`.

I have also tried putting my entire Snap app (in Haskell) behind `behindProxy X_Forwarded_For $` but that doesn't work either.

This is my nginx setup:

```
location / {
    proxy_set_header X-Real-IP       $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host            $http_host;
    proxy_set_header X-NginX-Proxy   true;

    proxy_pass http://127.0.0.1:4567/;
    proxy_redirect off;
}
```

What am I doing wrong?

**Comment by snap9** [comment]
For your information, `rqClientAddr` in my own Haskell code works perfectly to obtain the correct IP address. (When I run my Snap app with `--proxy=X_Forwarded_For`.)

It's just the **log file that gets the incorrect IP address**. Can you guys check the logging code? Maybe that's not using the correct forwarded IP address.

@mightybyte @gregorycollins

**Comment by sigrlami** [comment]
I can see this running snap app with Docker in Google Cloud, but not on standalone VM. On standalone VM x_forwarded_for is properly set, but rqClientAddr still gives local.

**Comment by karls** [comment]
I just wanted to comment that I'm seeing the same behaviour as @snap9 in `snap-core-0.9.8.0` -- the log file displays `127.0.0.1` no matter what I do, but asking for `rqClientAddr` in a `Handler` and printing that yields the correct IP.

**Comment by hvr** [comment]
What makes this even weirder is that the logging code appears to use `rqClientAddr` as well: https://github.com/snapframework/snap-server/blob/master/src/Snap/Http/Server.hs#L143

**Comment by sopvop** [comment]
I belive that `X_Forwarded_For` proxy code is part of handler executed by server, it operates on `request` as passed to user handler. And logging is part of server code which operates on original request. 

httpServe modifies the user `handler` with proxy and passes it to simpleHttpServe which then setups loggers and the rest.
```haskell
httpServe :: Config Snap a -> Snap () -> IO ()
httpServe config handler0 = do
    conf <- completeConfig config
    let !handler = chooseProxy conf
    let serve    = compress conf . catch500 conf $ handler
    simpleHttpServe conf serve
```

And then in httpSession the [handler is called with *original* request](https://github.com/snapframework/snap-server/blob/5c5b32de4ed653c963ce53e94bec278dba101a7f/src/Snap/Internal/Http/Server/Session.hs#L512), which when modifies request and calls users handler.
And at the bottom of same function [access log is written](https://github.com/snapframework/snap-server/blob/5c5b32de4ed653c963ce53e94bec278dba101a7f/src/Snap/Internal/Http/Server/Session.hs#L536) with unmodified request.

Fixing this would require to move proxy handling logic up the call chain instead of reusing the `behidProxy` combinator.

**Comment by gregorycollins** [comment]
Could you please confirm that aa989e3 fixes?
