### ISSUE TITLE
Time manager retains threads forever

### ISSUE THREAD

**Issue by Yuras** [snapframework/snap-server#99]
After switching to `snap-server-1.0.1.1` from `snap-server-0.9.5.1`, I see huge and increasing memory usage. It seems to be related to time manager retaining threads forever.

[`register`](https://github.com/snapframework/snap-server/blob/master/src/Snap/Internal/Http/Server/TimeoutManager.hs#L128) adds thread object to a list. It seems that [`cancel`](https://github.com/snapframework/snap-server/blob/master/src/Snap/Internal/Http/Server/TimeoutManager.hs#L174) should be used to remove it from the list, but I didn't find where it is called. So I added it as a cleanup [here](https://github.com/snapframework/snap-server/blob/master/src/Snap/Internal/Http/Server/Session.hs#L208). Also, `cancel` it not exception safe (e.g. `T.cancel` may fail, then `writeIORef` will not be called), so I guarded `writeIORef` with `finally`. Now my memory usage issue seems to be solved.

**Comment by mightybyte** [comment]
Hi there, and thanks for the bug report!  This definitely seems like a serious issue that we need to address.  @gregorycollins and I have been very busy lately, so we've gotten a little behind in snap maintenance.  Is there any chance you could put together a small self-contained test case to demonstrate this problem?  That would be a huge help to us in getting a fix released.  The ideal thing would be if we could get a failing test case.

**Comment by Yuras** [comment]
@mightybyte Thank you for the response.

It is hard to make a failing test case, but it is trivial to reproduce:

```
{-# LANGUAGE OverloadedStrings #-}

module Main where

import Snap.Core
import Snap.Http.Server

main :: IO ()
main = do
  httpServe defaultConfig $ route
    [ ("/test", method GET (return ()))
    ]

```

Compile with `ghc-8.0.1` and `snap-server-1.0.1.1`, run with `+RTS -S` to see memory usage online, and call the endpoint 1000 times:

```
for i in {0..1000} ; do
	echo $i
	curl http://localhost:8000/test
done
```

Note how live bytes grows linearly.

**Comment by Yuras** [comment]
I compiled the example above with profiling enabled and run with `+RTS -hy -xt`. It shows, that most of the memory is used by `STACK`. It confirms that worker threads are live (because their `ThreadId` is retained by time manager), so their stacks are not collected by GC:

![snap-server-leak](https://cloud.githubusercontent.com/assets/692251/24238235/a651ae60-0fba-11e7-993e-380be6de625c.png)

Running with `+RTS -hc -xt` shows, that memory is allocated by `forkIOLabeledWithUnmask`:

![snap-server-leak1](https://cloud.githubusercontent.com/assets/692251/24238293/e4b7f97a-0fba-11e7-8527-1ff74631e2a4.png)

**Comment by Yuras** [comment]
@mightybyte Just a friendly reminder. Were you able to reproduce it? Anything else I can do?

**Comment by levinem** [comment]
@Yuras, I am trying to replicate your example above.   I have compiled the Main.exe file using your  sample Main.hs text you suggested above, but as I am a bit of a novice with this, are you typing the "for i in {0..1000} ; do
	echo $i
	curl http://localhost:8000/test
done" portion into ghci?

**Comment by Yuras** [comment]
@levinem Thank you for looking to it. No, the for loop in a bash script. You can put it into a file and run with `bash filename`. Or just run curl manually 1000 times :)

**Comment by gregorycollins** [comment]
Are the threads retained "forever"? ...because you've linked in plots that cover less than half a second of wall clock time. The timeout manager runs in a polling loop and the hardcoded wakeup interval is 2 seconds, i.e. if you throw sustained load at the server the expected plot is expected to look like a sawtooth wave. See the implementation of TimeoutManager as well as the initialization point in [`Session.hs`](https://github.com/snapframework/snap-server/blob/b7ef5a1348c3f01456d77c2ef7177ecb216c9476/src/Snap/Internal/Http/Server/Session.hs#L218).

**Comment by gregorycollins** [comment]
....as for why it's written this way: this is a standard queuing theory thing. In general, it's usually the case that you can trade off latency for throughput by controlling batch size. As batch size increases, throughput increases (hot caches, fewer context switches, etc), but latency and RAM/disk requirements also increase because items are sitting around in buffers waiting to be processed.

In this specific case, best latency would be achieved if we could set a batch size of one (the timeout thread goes to sleep until the next thread's timeout and wakes up whenever one dies), but overall server throughput would suffer because we'd be spending time context switching into the timeout manager thread instead of serving user requests. The consequence is that you spend RAM for stacks you aren't using (and other associated bookkeeping data).

How much? The wakeup interval is 2 seconds, so if you're averaging `N` QPS then you'll be spending `2N * 16kB` on stacks. For `N=10000` that's 313MB of wastage, which is OK but is actually more than I was expecting. I have some ideas about how to improve the situation.

**Comment by gregorycollins** [comment]
Follow-up: however you're right that `cancel` isn't being called right now, and that's an oversight. This makes the problem worse, since the timeout thread will hold the `ThreadIds` for the entire timeout interval.
